### ISSUE TITLE
get device rotation when connecting?

### ISSUE THREAD

**Issue by el-quinto** [monome/serialosc.maxpat#2]
doesn't seem to be a way to do so. if i print out the first outlet i don't see any sys/rotation messages.

**Comment by tehn** [comment]
indeed, it is not reported. it sounds like this is something you need?

**Comment by el-quinto** [comment]
i just noticed /sys/id, /sys/size, and /sys/rotation are not reported. i used this info in the previous sosc.maxpat.

**Comment by tehn** [comment]
id is reported out of one of the other outlets-- check them out. i'll get
rotation and size into the next revision.
